version: 2
updates:
  - package-ecosystem: "npm"             # Экосистема для которой будут проверяться зависимости (npm)
    directory: "/"                       # Директория, где находится package.json
    schedule:
      interval: "daily"                 # Интервал проверки (еженедельно)
    commit-message:
      prefix: "deps"                     # Префикс для сообщений коммитов в PR
      include: "scope"                   # Включить название библиотеки в сообщение коммита
    open-pull-requests-limit: 10         # Максимальное количество открытых PR
    rebase-strategy: "auto"              # Автоматический ребейз PR
    versioning-strategy: "increase"      # Стратегия обновления: "increase", "widen", "lockfile-only", или "auto"
    labels:
      - "dependencies"                   # Метка, которая будет автоматически добавляться к создаваемым PR
    reviewers:
      - "makarasty"                      # Назначить пользователей на PR для ревью (укажите свои)
    assignees:
      - "makarasty"                      # Назначить пользователей ответственными за PR
    target-branch: "main"                # Целевая ветка для PR (можно указать другую ветку)
